apiVersion: v2
name: yt-playlist
description: YouTube Playlist Manager - Automated video downloader with playlist management
type: application
version: 1.0.7
appVersion: "latest"
keywords:
  - youtube
  - downloader
  - playlist
  - yt-dlp
home: https://github.com/L4R5/yt-playlist
maintainers:
  - name: L4R5
    url: https://github.com/L4R5
