{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    {{- include "yt-playlist.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.clientSecretJson }}
  CLIENT_SECRET_JSON: {{ .Values.clientSecretJson | b64enc | quote }}
  client_secret.json: {{ .Values.clientSecretJson | b64enc | quote }}
  {{- end }}
{{- end }}
